final mockLoginResponse = {
  'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9',
  'userId': 'emp_12345',
  'email': 'test@example.com',
  'fullName': 'John Doe',
};

final mockUserResponse = {
  'id': 'emp_12345',
  'email': 'test@example.com',
  'fullName': 'John Doe',
  'role': 'Senior Developer',
  'avatar': 'https://api.example.com/avatars/john.jpg',
  'department': 'Engineering',
};

final mockStatsResponse = {'attendance': 22, 'leaves': 5, 'requests': 2};

final mockLeavesResponse = [
  {
    'id': 'leave_1',
    'type': 'Casual Leave',
    'startDate': '2024-04-10',
    'endDate': '2024-04-12',
    'status': 'Approved',
    'duration': '3 Days',
    'reason': 'Family function out of town',
    'appliedOn': '2024-04-01',
    'approvedBy': 'Sarah Jenkins (HR)',
  },
  {
    'id': 'leave_2',
    'type': 'Sick Leave',
    'startDate': '2024-03-28',
    'endDate': '2024-03-29',
    'status': 'Approved',
    'duration': '2 Days',
    'reason': 'Viral fever and prescribed rest',
    'appliedOn': '2024-03-28',
    'approvedBy': 'Auto-approved (System)',
  },
  {
    'id': 'leave_3',
    'type': 'Casual Leave',
    'startDate': '2024-04-20',
    'endDate': '2024-04-22',
    'status': 'Pending',
    'duration': '3 Days',
    'reason': 'Personal errands',
    'appliedOn': '2024-04-06',
    'approvedBy': null,
  },
  {
    'id': 'leave_4',
    'type': 'Maternity Leave',
    'startDate': '2024-05-01',
    'endDate': '2024-08-01',
    'status': 'Approved',
    'duration': '92 Days',
    'reason': 'Maternity leave',
    'appliedOn': '2024-03-15',
    'approvedBy': 'HR Manager',
  },
  {
    'id': 'leave_5',
    'type': 'Earned Leave',
    'startDate': '2024-04-25',
    'endDate': '2024-04-26',
    'status': 'Approved',
    'duration': '2 Days',
    'reason': 'Personal work',
    'appliedOn': '2024-04-10',
    'approvedBy': 'Manager Approval',
  },
  {
    'id': 'leave_6',
    'type': 'Sick Leave',
    'startDate': '2024-03-15',
    'endDate': '2024-03-16',
    'status': 'Approved',
    'duration': '2 Days',
    'reason': 'Medical check-up',
    'appliedOn': '2024-03-15',
    'approvedBy': 'Auto-approved (System)',
  },
  {
    'id': 'leave_7',
    'type': 'Casual Leave',
    'startDate': '2024-05-10',
    'endDate': '2024-05-12',
    'status': 'Rejected',
    'duration': '3 Days',
    'reason': 'Vacation plans',
    'appliedOn': '2024-04-28',
    'approvedBy': 'Manager Denial',
  },
  {
    'id': 'leave_8',
    'type': 'Paternity Leave',
    'startDate': '2024-06-01',
    'endDate': '2024-06-15',
    'status': 'Pending',
    'duration': '15 Days',
    'reason': 'Birth of child',
    'appliedOn': '2024-05-15',
    'approvedBy': null,
  },
  {
    'id': 'leave_9',
    'type': 'Half Day',
    'startDate': '2024-03-20',
    'endDate': '2024-03-20',
    'status': 'Approved',
    'duration': '0.5 Days',
    'reason': 'Doctor appointment',
    'appliedOn': '2024-03-20',
    'approvedBy': 'Auto-approved (System)',
  },
  {
    'id': 'leave_10',
    'type': 'Earned Leave',
    'startDate': '2024-04-30',
    'endDate': '2024-05-05',
    'status': 'Approved',
    'duration': '6 Days',
    'reason': 'Summer vacation',
    'appliedOn': '2024-04-15',
    'approvedBy': 'Sarah Jenkins (HR)',
  },
  {
    'id': 'leave_11',
    'type': 'Compassionate Leave',
    'startDate': '2024-02-15',
    'endDate': '2024-02-17',
    'status': 'Approved',
    'duration': '3 Days',
    'reason': 'Family emergency',
    'appliedOn': '2024-02-15',
    'approvedBy': 'Manager Approval',
  },
  {
    'id': 'leave_12',
    'type': 'Casual Leave',
    'startDate': '2024-03-05',
    'endDate': '2024-03-08',
    'status': 'Approved',
    'duration': '4 Days',
    'reason': 'Personal vacation',
    'appliedOn': '2024-02-20',
    'approvedBy': 'Sarah Jenkins (HR)',
  },
  {
    'id': 'leave_13',
    'type': 'Sick Leave',
    'startDate': '2024-02-22',
    'endDate': '2024-02-23',
    'status': 'Approved',
    'duration': '2 Days',
    'reason': 'Cold and flu',
    'appliedOn': '2024-02-22',
    'approvedBy': 'Auto-approved (System)',
  },
  {
    'id': 'leave_14',
    'type': 'Earned Leave',
    'startDate': '2024-06-10',
    'endDate': '2024-06-14',
    'status': 'Pending',
    'duration': '5 Days',
    'reason': 'Planned trip',
    'appliedOn': '2024-05-25',
    'approvedBy': null,
  },
  {
    'id': 'leave_15',
    'type': 'Half Day',
    'startDate': '2024-04-18',
    'endDate': '2024-04-18',
    'status': 'Approved',
    'duration': '0.5 Days',
    'reason': 'Dental appointment',
    'appliedOn': '2024-04-18',
    'approvedBy': 'Auto-approved (System)',
  },
  {
    'id': 'leave_16',
    'type': 'Casual Leave',
    'startDate': '2024-05-20',
    'endDate': '2024-05-22',
    'status': 'Approved',
    'duration': '3 Days',
    'reason': 'Wedding function',
    'appliedOn': '2024-05-05',
    'approvedBy': 'Manager Approval',
  },
  {
    'id': 'leave_17',
    'type': 'Sick Leave',
    'startDate': '2024-03-10',
    'endDate': '2024-03-11',
    'status': 'Approved',
    'duration': '2 Days',
    'reason': 'Migraine treatment',
    'appliedOn': '2024-03-10',
    'approvedBy': 'Auto-approved (System)',
  },
  {
    'id': 'leave_18',
    'type': 'Earned Leave',
    'startDate': '2024-04-30',
    'endDate': '2024-05-02',
    'status': 'Rejected',
    'duration': '3 Days',
    'reason': 'Annual leave request',
    'appliedOn': '2024-04-15',
    'approvedBy': 'Manager Denial',
  },
  {
    'id': 'leave_19',
    'type': 'Casual Leave',
    'startDate': '2024-06-01',
    'endDate': '2024-06-02',
    'status': 'Pending',
    'duration': '2 Days',
    'reason': 'Friend visit',
    'appliedOn': '2024-05-20',
    'approvedBy': null,
  },
  {
    'id': 'leave_20',
    'type': 'Half Day',
    'startDate': '2024-04-08',
    'endDate': '2024-04-08',
    'status': 'Approved',
    'duration': '0.5 Days',
    'reason': 'Eye checkup',
    'appliedOn': '2024-04-08',
    'approvedBy': 'Auto-approved (System)',
  },
];

final mockHolidaysResponse = [
  {'id': 'holiday_1', 'name': 'Good Friday', 'date': '2024-03-29'},
  {'id': 'holiday_2', 'name': 'Easter Monday', 'date': '2024-04-01'},
  {'id': 'holiday_3', 'name': 'Labour Day', 'date': '2024-05-01'},
  {'id': 'holiday_4', 'name': 'Bank Holiday', 'date': '2024-05-06'},
  {'id': 'holiday_5', 'name': 'Summer Bank Holiday', 'date': '2024-05-27'},
  {'id': 'holiday_6', 'name': 'Independence Day', 'date': '2024-08-15'},
  {'id': 'holiday_7', 'name': 'Diwali', 'date': '2024-11-01'},
  {'id': 'holiday_8', 'name': 'Christmas', 'date': '2024-12-25'},
  {'id': 'holiday_9', 'name': 'New Year Day', 'date': '2025-01-01'},
  {'id': 'holiday_10', 'name': 'Republic Day', 'date': '2025-01-26'},
  {'id': 'holiday_11', 'name': 'Holi', 'date': '2025-03-14'},
  {'id': 'holiday_12', 'name': 'Good Friday', 'date': '2025-04-18'},
  {'id': 'holiday_13', 'name': 'Easter Monday', 'date': '2025-04-21'},
  {'id': 'holiday_14', 'name': 'Labour Day', 'date': '2025-05-01'},
  {'id': 'holiday_15', 'name': 'Buddha Purnima', 'date': '2025-05-05'},
  {'id': 'holiday_16', 'name': 'Summer Bank Holiday', 'date': '2025-05-26'},
  {'id': 'holiday_17', 'name': 'Independence Day', 'date': '2025-08-15'},
  {'id': 'holiday_18', 'name': 'Janmashtami', 'date': '2025-08-27'},
  {'id': 'holiday_19', 'name': 'Diwali', 'date': '2025-10-20'},
  {'id': 'holiday_20', 'name': 'Christmas', 'date': '2025-12-25'},
];

final mockAttendanceResponse = [
  {
    'id': 'att_1',
    'date': '2024-04-05',
    'checkIn': '09:15 AM',
    'checkOut': '06:30 PM',
    'status': 'Present',
    'workHours': '9h 15m',
    'location': 'Office',
    'notes': 'Late arrival by 15 mins',
  },
  {
    'id': 'att_2',
    'date': '2024-04-04',
    'checkIn': '09:00 AM',
    'checkOut': '06:15 PM',
    'status': 'Present',
    'workHours': '9h 15m',
    'location': 'Remote',
    'notes': 'Worked from home (Approved)',
  },
  {
    'id': 'att_3',
    'date': '2024-04-03',
    'checkIn': '10:30 AM',
    'checkOut': '05:45 PM',
    'status': 'Half Day',
    'workHours': '7h 15m',
    'location': 'Office',
    'notes': 'Half day leave applied',
  },
  {
    'id': 'att_4',
    'date': '2024-04-02',
    'checkIn': '09:10 AM',
    'checkOut': '06:20 PM',
    'status': 'Present',
    'workHours': '9h 10m',
    'location': 'Client Site',
    'notes': 'On-site meeting at Nexus Corp',
  },
  {
    'id': 'att_5',
    'date': '2024-04-01',
    'checkIn': 'N/A',
    'checkOut': null,
    'status': 'Absent',
    'workHours': '0h 0m',
    'location': 'N/A',
    'notes': 'Uninformed absence',
  },
  {
    'id': 'att_6',
    'date': '2024-03-31',
    'checkIn': '08:55 AM',
    'checkOut': '06:10 PM',
    'status': 'Present',
    'workHours': '9h 15m',
    'location': 'Office',
    'notes': 'Normal working day',
  },
  {
    'id': 'att_7',
    'date': '2024-03-30',
    'checkIn': '09:20 AM',
    'checkOut': '06:35 PM',
    'status': 'Present',
    'workHours': '9h 15m',
    'location': 'Remote',
    'notes': 'Worked from home',
  },
  {
    'id': 'att_8',
    'date': '2024-03-29',
    'checkIn': '09:05 AM',
    'checkOut': '06:00 PM',
    'status': 'Present',
    'workHours': '8h 55m',
    'location': 'Office',
    'notes': 'Early departure approved',
  },
  {
    'id': 'att_9',
    'date': '2024-03-28',
    'checkIn': 'N/A',
    'checkOut': null,
    'status': 'Leave',
    'workHours': '0h 0m',
    'location': 'N/A',
    'notes': 'Casual leave',
  },
  {
    'id': 'att_10',
    'date': '2024-03-27',
    'checkIn': '09:10 AM',
    'checkOut': '06:25 PM',
    'status': 'Present',
    'workHours': '9h 15m',
    'location': 'Office',
    'notes': 'Regular working day',
  },
  {
    'id': 'att_11',
    'date': '2024-03-26',
    'checkIn': '09:00 AM',
    'checkOut': '06:00 PM',
    'status': 'Present',
    'workHours': '9h 0m',
    'location': 'Client Site',
    'notes': 'Client meeting and follow-up',
  },
  {
    'id': 'att_12',
    'date': '2024-03-25',
    'checkIn': '09:30 AM',
    'checkOut': '06:30 PM',
    'status': 'Present',
    'workHours': '9h 0m',
    'location': 'Remote',
    'notes': 'WFH - Project deadline work',
  },
  {
    'id': 'att_13',
    'date': '2024-03-24',
    'checkIn': '08:45 AM',
    'checkOut': '05:45 PM',
    'status': 'Present',
    'workHours': '9h 0m',
    'location': 'Office',
    'notes': 'Regular shift',
  },
  {
    'id': 'att_14',
    'date': '2024-03-23',
    'checkIn': '09:15 AM',
    'checkOut': '06:30 PM',
    'status': 'Present',
    'workHours': '9h 15m',
    'location': 'Office',
    'notes': 'Team meeting and code review',
  },
  {
    'id': 'att_15',
    'date': '2024-03-22',
    'checkIn': 'N/A',
    'checkOut': null,
    'status': 'Absent',
    'workHours': '0h 0m',
    'location': 'N/A',
    'notes': 'Sick leave - fever',
  },
  {
    'id': 'att_16',
    'date': '2024-03-21',
    'checkIn': '10:00 AM',
    'checkOut': '05:00 PM',
    'status': 'Half Day',
    'workHours': '7h 0m',
    'location': 'Office',
    'notes': 'Doctor appointment',
  },
  {
    'id': 'att_17',
    'date': '2024-03-20',
    'checkIn': '09:05 AM',
    'checkOut': '06:20 PM',
    'status': 'Present',
    'workHours': '9h 15m',
    'location': 'Remote',
    'notes': 'Worked from home - stable connection',
  },
  {
    'id': 'att_18',
    'date': '2024-03-19',
    'checkIn': '09:20 AM',
    'checkOut': '06:35 PM',
    'status': 'Present',
    'workHours': '9h 15m',
    'location': 'Office',
    'notes': 'Late by 20 mins but made up the time',
  },
  {
    'id': 'att_19',
    'date': '2024-03-18',
    'checkIn': '09:00 AM',
    'checkOut': '07:00 PM',
    'status': 'Present',
    'workHours': '10h 0m',
    'location': 'Office',
    'notes': 'Project deadline - extra hours',
  },
  {
    'id': 'att_20',
    'date': '2024-03-17',
    'checkIn': '09:10 AM',
    'checkOut': '06:15 PM',
    'status': 'Present',
    'workHours': '9h 5m',
    'location': 'Client Site',
    'notes': 'On-site workshop',
  },
];
